PennLINC/babs

setup.py

change package name from BABS to babs in setup.py

---

LICENSE
setup.cfg

Make sure it's consistent to be MIT license.

[FIX] metadata in setup.cfg regarding license

---

babs/babs.py
babs/dict_cluster_systems.yaml
babs/utils.py

- adding commands for slurm 
- some refactoring of `generate_job_submit_template`

[ENH] adding slurm as a system type

---

docs/source/installation.rst
docs/source/preparation_config_yaml_file.rst
docs/source/walkthrough.rst
notebooks/eg_toybidsapp-0-0-7_rawBIDS-walkthrough_sge_cubic.yaml

@zhao-cy - I've tested the example on our cluster and I added a few suggestions to the documentation. 
I think the most important is that some combination of the cluster settings might not work (setting `temporary_disk_space` leads to the error in my case). I've also specified the version of Singularity that I used for testing, since I had problem with building the singularity image from your docker image using my previously default version that was older.
Overall, I think the document looks great, the instructions are very detailed, so hopefully everyone should be able to follow!
Some additional comments/suggestions:
- any reason why you sometimes use `${PWD}` and sometimes `$PWD`?
- are you sure that ` Provide your OSF credentials (token) - this step is very important!`?  
- I've …

Revisions in docs after testing on MIT slurm cluster

---

README.rst

[DOCS] add DOI link to zenodo archive

---

docs/source/babs-check-setup.rst
docs/source/preparation_input_dataset.rst
setup.cfg

This PR will update docs for paper revision.

[DOCS] update docs during paper revision

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yml
.github/ISSUE_TEMPLATE/feature_request.md
setup.cfg

References #110.
Changes proposed:
- Add bug report and feature request templates.
- Add link to NeuroStars for usage questions.

Add issue templates

---

docs/source/walkthrough.rst

Minor change after PR #159: I added a bit more explanations on when Step 0 is required/optional/suggested.

[DOCS] minor changes in eg walkthrough: explain when Step 0 is optional

---

babs/babs.py
babs/cli.py
babs/utils.py
tests/test_babs_check_setup.py
tests/test_babs_init.py

Closes https://github.com/PennLINC/babs/issues/175

Support SLURM array jobs in `babs-submit`

---

.github/workflows/shellcheck.yml

I broke shellcheck's GHA test, this fixes it

Fix shellcheck

---

babs/babs.py

containall, writable-tmpfs, absolute paths

---

.github/workflows/shellcheck.yml

would also make it easier to just remove scripts without needing to adjust workflow ;-)

Do shellcheck all the shell scripts

---

babs/utils.py
tox.ini

Replace `pkg_resources` with `importlib.metadata`

---

babs/babs.py

change how subject ID and session ID are parsed from the jobs CSV

---

babs/babs.py
babs/utils.py

Remove commented-out code

---

babs/generate_submit_script.py

I mixed up TASK_ID with JOB_ID, which caused some confusing errors

Fix SLURM JOB_ID bug

---

.gitignore
babs/babs.py
notebooks/eg_qsirecon-1-0-1_custom_spec.yaml
notebooks/eg_toybidsapp-0-0-7_rawBIDS-walkthrough.yaml
tests/e2e-slurm/container/walkthrough-tests.sh
tests/test_babs_init.py

Add imported_files section to config files

---

babs/cli.py

Fix `message` / `commit-message` argument names

Fix `sync-code`

---

babs/templates/participant_job.sh.jinja2
babs/update.py

Closes https://github.com/PennLINC/babs/issues/300.

Fix jinja space rendering issue for `participant_job.sh`

---

babs/generate_bidsapp_runscript.py
notebooks/eg_freesurferpost-unstable_ingressed-fs.yaml
pyproject.toml

We needed a way to specify a --session-id flag. This will probably be useful in other software as the session-level processing becomes more common.

Add freesurfer-post
